version: 2.1

orbs:
  python: rohanpm/python@1.3.0

workflows:
  tests:
    jobs:
      # - test-linux
      - test-mac

jobs:
  test-linux:
    name: "Run test suite on Linux with Python 3.8"
    executor: python/python38

    steps:
      - checkout
      - run: pip install tox
      - env: TOXENV=py3.8
      - run:
          name: Test
          command: tox

  test-mac:
    macos:
      xcode: 11.6.0
    steps:
      - checkout
      - run: pip install tox
      - env: TOXENV=py3.8
      - run:
          name: Test
          command: tox
