version: 2.1

orbs:
  python: rohanpm/python@1.3.0

workflows:
  tests:
    jobs:
      - test-linux
      # - test-mac

jobs:
  test-linux:
    executor: python/python38

    steps:
      - checkout
      - run: pip install tox
      - run:
          name: Test
          command: tox

  test-mac:
    macos:
      xcode: 11.6.0
    steps:
      - checkout
      - run: pip install tox
      - run:
          name: Test
          command: tox
